DATAS SEGMENT
    MSR DB "HELLO,WORLD!$" 
	LEN EQU $ - MSR
DATAS ENDS

EXDA SEGMENT 
	MSD DB LEN DUP(?) 
EXDA ENDS

STACKS SEGMENT
	DW 20 DUP(?)
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,ES:EXDA,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    MOV AX, EXDA 
	MOV ES,AX 
    MOV SI,OFFSET MSR ;设置SI 
	MOV DI,OFFSET MSD ;设置DI 
	MOV CX, LEN 
NEXT: 
	MOV AL,[SI] ;开始传输数据
	MOV ES:[DI],AL
	INC SI 
	INC DI 
	DEC CX 
	JNZ NEXT 
	PUSH ES 
	POP DS ;将附加段寄存器的段值赋给数据段寄存器
	MOV DX, OFFSET MSD 
	MOV AH, 9 
	INT 21H 
	MOV AX, 4C00H ;利用DOS功能调用返回DOS状态
	INT 21H
CODES ENDS
    END START

